[settings]
pokemon_pokeball_mapping = {
    "Shieldon": "greatball",
    "Machoke": "greatball",
    "Magikarp": "greatball"
    }

ENABLE_AUTO_BUY_BALLS=True

ENABLE_AUTO_RELEASE_DUPLICATES=False

ENABLE_AUTO_EGG_HATCH=True

# [ENABLE_AUTO_LOOTBOX_OPEN]
# It will open lootboxes when you have 10 or more
ENABLE_AUTO_LOOTBOX_OPEN=True

# [ENABLE_FISHING] 
# It will fish every 3 catches
ENABLE_FISHING=True